# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'TBTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TBTestApp
  pod 'Kingfisher', '~> 5.0'
  pod 'Swinject'
  pod 'SwiftLint'
  
  target 'TBTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
